version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/dev/Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./app:/app
    env_file:
      - ./.envs/.dev/.app
      - ./.envs/.dev/.postgres
    ports:
      - "8000:8000"
    command: "python manage.py runserver 0.0.0.0:8000"
    environment:
      - TZ=Europe/Berlin

  postgres:
    image: "postgres:13.1"
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - ./.envs/.dev/.postgres
    environment:
      - TZ=Europe/Berlin

volumes:
  database: